name: Deploy to Oracle Patent Hash Backend Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.OCI_HOST }}
          username: ${{ secrets.OCI_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: ${{ secrets.OCI_SSH_PORT }}
          script: |
            cd github/backend
            bash scripts/deploy-oci.sh